#!/bin/bash

#SBATCH --partition=long
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=8G
#SBATCH --job-name=align_to_ref
#SBATCH --output=logs/align_%A_%a.out
#SBATCH --error=logs/align_%A_%a.err
#SBATCH --array=1-999%20

set -euo pipefail

START_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "Script started at: $START_TIME"

# Load environment

source /private/groups/kaylab/aschjeld/setup_conda.sh

# Temporarily allows undefined variables as errors then turns strict mode back on 
set +u
conda activate popoolation2
set -u

# Specify directories and files
READDIR="/private/groups/kaylab/popoolation2/populations/fullpops/JR3/3p_fastq_split"
REF="/private/groups/kaylab/popoolation2/populations/scaffolded_assemblies/LPJR3B2_primary_scaffolds_final.fa"
OUTDIR="/private/groups/kaylab/popoolation2/populations/fullpops/JR3/pop3p_bam_output"

mkdir -p "$OUTDIR" logs

FASTQ=$(printf "%s/pop3p.part_%03d.fastq.gz" "$READDIR" "$SLURM_ARRAY_TASK_ID")
BASE=$(basename "$FASTQ" .fastq.gz)

# command to align split fastq to the reference genome
# -t 8 specifies threads to use. 

bwa mem -t 8 "$REF" "$FASTQ" \
  | samtools view -bS - \
  | samtools sort -@ 8 -o "$OUTDIR/${BASE}.sorted.bam" -

samtools index "$OUTDIR/${BASE}.sorted.bam"

echo "Done: $OUTDIR/${BASE}.sorted.bam"

END_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "Script ended at: $END_TIME"
