#!/bin/bash

# Script to merge all pink pools and white pools, respectively, and organize them in files according to scaffold. 
# All BAMs correspionding to each scaffold are put in respective files and re-indexed to create a new BAM and BAI of
# across-site pink- and white-flowered individuals. 
# Doing this in BAM format preserves mapping quality, base quality, depth, allele counts, and alignment position. 

#SBATCH --partition=medium
#SBATCH --time=6:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --job-name=merge_by_scaffold
#SBATCH --output=logs/merge_scaffold_%A_%a.out
#SBATCH --error=logs/merge_scaffold_%A_%a.err
#SBATCH --array=1594-2630%10

# Activate strict debug mode to stop the script if a command fails, if an unidentified variable is used, and to print 
# each command as it runs. This helps debugging, so I can tell how far the script got and keep it from running through
# faulty commands if they are accidentally present.
set -euo pipefail

# Load conda environment for the PoPoolation2 pipeline
source /private/groups/kaylab/aschjeld/setup_conda.sh

set +u
conda activate popoolation2
set -u

# Specify the location of the reference genome .fai file. This file tells us the scaffold number and its length. 
ref_fai="/private/groups/kaylab/popoolation2/populations/scaffolded_assemblies/LPJR3B2_primary_scaffolds_final.fa.fai"

# Specify the output directory and make sure this directory exists. 
outdir="/private/groups/kaylab/popoolation2/populations/fullpops/popacross/scaffold_bams"
mkdir -p "$outdir" logs

# Uses the Slurm array task ID to choose one scaffold from the .fai file. 
scaffold=$(awk -v n="$SLURM_ARRAY_TASK_ID" 'NR==n {print $1}' "$ref_fai")

echo "Working on scaffold: $scaffold"

# Defines the file patchs that will store all pink and white BAMs.
pink_list="$outdir/all_pink_bams.txt"
white_list="$outdir/all_white_bams.txt"

# Navigate to each directory with BAMs so they can be combined by flower color. 
JR1P="/private/groups/kaylab/popoolation2/populations/fullpops/JR1/pop1p_bam_output"
JR2P="/private/groups/kaylab/popoolation2/populations/fullpops/JR2/pop2p_bam_output"
JR3P="/private/groups/kaylab/popoolation2/populations/fullpops/JR3/step1_split_fastq/pop3p_bam_output"
JR4P="/private/groups/kaylab/popoolation2/populations/fullpops/JR4/step1_split_fastq/pop4p_bam_output"

# Defines the directories containing pink BAMs from each patch. This finds all pink .filtered.bam files and writes
# their paths into the all_pink_bams.txt file. 
find "$JR1P" "$JR2P" "$JR3P" "$JR4P" \
  -maxdepth 1 \
  -name "*.filtered.bam" \
  | sort > "$pink_list"

echo "Pink list:"
wc -l "$pink_list"
head "$pink_list"

# Same as the pink above. 
JR1W="/private/groups/kaylab/popoolation2/populations/fullpops/JR1/pop1w_bam_output"
JR2W="/private/groups/kaylab/popoolation2/populations/fullpops/JR2/pop2w_bam_output"
JR3W="/private/groups/kaylab/popoolation2/populations/fullpops/JR3/step1_split_fastq/pop3w_bam_output"
JR4W="/private/groups/kaylab/popoolation2/populations/fullpops/JR4/step1_split_fastq/pop4w_bam_output"

# Same at the pink above. 
find "$JR1W" "$JR2W" "$JR3W" "$JR4W" \
  -maxdepth 1 \
  -name "*.filtered.bam" \
  | sort > "$white_list"

echo "White list:"
wc -l "$white_list"
head "$white_list"

# Check they exist
wc -l "$pink_list" "$white_list"

# If any BAMs were missing their corresponding .BAI file, index them. 
while read -r bam; do
    if [[ ! -f "${bam}.bai" ]]; then
        echo "Indexing: $bam"
        samtools index "$bam"
    fi
done < "$pink_list"

# Now index missing white BAM indexes
while read -r bam; do
    if [[ ! -f "${bam}.bai" ]]; then
        echo "Indexing: $bam"
        samtools index "$bam"
    fi
done < "$white_list"

# Specify output name by color and scaffold
pink_out="$outdir/all_pink_${scaffold}.bam"
white_out="$outdir/all_white_${scaffold}.bam"

# Temporary batch directories for this scaffold
pink_batch_dir="$outdir/tmp_pink_batches_${scaffold}"
white_batch_dir="$outdir/tmp_white_batches_${scaffold}"

mkdir -p "$pink_batch_dir" "$white_batch_dir"

# Split the BAM list into smaller lists of 100 BAMs each to avoid "too many open files" error during merge. 
split -l 100 "$pink_list" "$pink_batch_dir/pink_list_"

pink_batch_bams="$pink_batch_dir/pink_batch_bams.txt"
: > "$pink_batch_bams"

# For the files in each directory, merge based on scaffold. Then index it. 
for list in "$pink_batch_dir"/pink_list_*; do
    base=$(basename "$list")
    batch_bam="$pink_batch_dir/${base}.bam"

    echo "Merging pink batch: $base for $scaffold"

    samtools merge -@ 8 -R "$scaffold" -b "$list" "$batch_bam"
    samtools index "$batch_bam"

    echo "$batch_bam" >> "$pink_batch_bams"
done

echo "Merging final pink BAM for $scaffold"

samtools merge -@ 8 -R "$scaffold" -b "$pink_batch_bams" "$pink_out"
samtools index "$pink_out"


# White batch merge, same as above pink. 
split -l 100 "$white_list" "$white_batch_dir/white_list_"

white_batch_bams="$white_batch_dir/white_batch_bams.txt"
: > "$white_batch_bams"

for list in "$white_batch_dir"/white_list_*; do
    base=$(basename "$list")
    batch_bam="$white_batch_dir/${base}.bam"

    echo "Merging white batch: $base for $scaffold"

    samtools merge -@ 8 -R "$scaffold" -b "$list" "$batch_bam"
    samtools index "$batch_bam"

    echo "$batch_bam" >> "$white_batch_bams"
done

echo "Done: $scaffold"
