#!/bin/bash

#SBATCH --job-name=JR1_pop1p_QC
#SBATCH --partition=medium
#SBATCH --time=4:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --output=JR1_pop1p_QC.out
#SBATCH --error=JR1_pop1p_QC.err

# Sequence of commands that extract qquality control stats: read depth, coverage, and proportion of reads mapped to the reference genome. 
# Adapted from https://sarahpenir.github.io/bioinformatics/awk/calculating-mapping-stats-from-a-bam-file-using-samtools-and-awk/

set -euo pipefail

source /private/groups/kaylab/aschjeld/setup_conda.sh
set +u
conda activate popoolation2
set -u

# Mean read depth that computes the depth at each position or region. The -a flag indicates that 
# the depth must include all positions, including those with zero depth. 
# This creates three columns that describe the reference sequence name, the 1-based leftmost 
# mapping position, and the depth at the position, respectively. 

samtools depth -a pop1p_merged.filtered.bam | awk '{c++;s+=$3}END{print s/c}' \
> JR1_pop1p_QC.txt

# this is a pipe that passes the output from samtools depth to awk, which calculates
# two variables, c (the total number of positions) and s (the cumulative depth across all positions).
# The mean read depth is s/c


# Similarly, this pipes the value from samtools depth to calculate the totala number of positions,c,
# and "total" which receives an increment of 1 when the depth is greater than 0. 
# The breadth of coverage is (total/c)*100. 
samtools depth -a pop1p_merged.filtered.bam | awk '{c++; if($3>0) total+=1}END{print (total/c)*100}' \
> JR1_pop1p_QC.txt

# Proportion of reads mapped to the reference genome
# samtools flagstat passes through the whole file to print important stats 
samtools flagstat pop1p_merged.filtered.bam | awk -F "[(1%)]" 'NR == 3 {print $2}' \
> JR1_pop1p_QC.txt
