#!/bin/bash

# Script to index the primary scaffolded reference genome LPJR3B2_primary_scaffolds_final.fa using bwa index.

#SBATCH --job-name=index_primary_ref
#SBATCH --partition=long
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=64G
#SBATCH --output=index.out
#SBATCH --error=index.err

# Exit job if anything fails
set -eo pipefail

# load environment
source /private/groups/kaylab/aschjeld/setup_conda.sh

set +u
export JAVA_LD_LIBRARY_PATH="${JAVA_LD_LIBRARY_PATH:-}"
export PERL5LIB="${PERL5LIB:-}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"
conda activate popoolation2
set -u

# print version (bwa index doesnt respond to --version)
bwa 2>&1 | head -n 3 || true

# print start time and date
START_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "Script started at: $START_TIME"

# primary command to run index over the reference genome
# this function prepares a reference genome is FASTA format for fast alignment by creating an FM-index that includes several files.
# this later allows for rapid mapping of short sequencing reads to the reference. 
bwa index LPJR3B2_primary_scaffolds_final.fa  

echo "index complete"

# print end time and date
END_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "Script ended at: $END_TIME"
