#!/bin/bash 

# This script takes the previously made mpileup file and converts it to a sync file. 

#SBATCH --partition=long
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --job-name=mpile_to_sync
#SBATCH --output=mmpile_to_sync.out
#SBATCH --error=mpile_to_sync.err

# End script if a command fails, if an undefined variable is used, or if any command in a pipe fails. 
set -euo pipefail

# Print start date and time. 
START_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "Script started at: $START_TIME"

# Load environment
source /private/groups/kaylab/aschjeld/setup_conda.sh


# Temporarily allows undefined variables during conda activation, then disables it again. 
set +u
conda activate popoolation2
set -u

# Set directories 
POPDIR="/private/groups/kaylab/popoolation2/populations/popoolation2_1201"
MPILEUP_OUT="3p_3w.mpileup"
SYNC_OUT="3p_3w.sync"

# debugging
pwd
ls -lh $POPDIR
which java
java -version

# Convert mpileup to sync
# -ea enables Java assertions, -Xmx7g allows Java to use up to 7GB of RAM, -jaw run the popoolation2 conversion tool
# --fastq-type specfies the types of reads used. We did not use sanger sequencing, but for the purpose of this script, it is okay. 
# -min-qual of 20 ignores bases with base quality below 20, and --threads specifies the number of threads to use. 
echo "Converting mpileup to sync..."
java -ea -Xmx7g -jar "$POPDIR/mpileup2sync.jar" \
    --input "$MPILEUP_OUT" \
    --output "$SYNC_OUT" \
    --fastq-type sanger \
    --min-qual 20 \
    --threads 8

echo "Done!"

# Print end date and time. 
END_TIME=$(date +"%Y-%m-%d %H:%M:%S")
echo "Script finished at: $END_TIME"
