#!/bin/bash

# This script calculates pairwise FST of pooled pink-flowered plants against pooled white-flowered plants using the PoPoolation2 workflow. 
# Individual patch FST and across-site FST (combining all pink and all white respectively) from Jasper Ridge Biological Preserve were estimated using this script. 

#SBATCH --job-name=fst
#SBATCH --partition=long
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --array=0-2619%20
#SBATCH --output=fst.out
#SBATCH --error=fst.err

# Load conda environment for the PoPoolation2 pipeline
source /private/groups/kaylab/aschjeld/setup_conda.sh
conda activate popoolation2

# Specify file path for Perl, so the correct moculde is used for the step below. Without this specification, the 
# incorrect Perl module is used. 
export PATH="$HOME/perl5/bin:$PATH"
export PERL5LIB="$HOME/perl5/lib/perl5:${PERL5LIB:-}"

# Forces a single language environment to avoid "locale" warnings. 
export LC_ALL=C
export LANG=C

# Activate strict debug mode to stop the script if a command fails, if an unidentified variable is used, and to print 
# each command as it runs. This helps debugging, so I can tell how far the script got and keep it from running through
# faulty commands if they are accidentally present.
set -euo pipefail
set -x

# Complete directory paths to the sync files, the output directory, and the primiary PoPoolation2 script, respectively.
# Defining them this way lets me refer to each file location easier. 
chunkdir="/private/groups/kaylab/popoolation2/populations/fullpops/JR3/sync_by_scaffold"
outdir="/private/groups/kaylab/popoolation2/populations/fullpops/JR3/fst"
script="/private/groups/kaylab/popoolation2/populations/popoolation2_1201/fst-sliding.pl"

# Ensure that the above output directories for .fst and error/output files exist. 
mkdir -p "$outdir" logs

# Go to the .sync file directory
cd "$chunkdir"

# Find all file in the .sync directory starting with "scaffold", sort them by number, and store them in a Bash array called "files"
mapfile -t files < <(find . -maxdepth 1 -type f -name "scaffold*" | sort)

# Check whether the correct Slurm array task number is larger than the number of files. If yes, it will exit here instead of crashing
# later on. 
if [[ "$slurm_array_task_id" -ge "${#files[@]}" ]]; then
  echo "No file for slurm_array_task_id=$slurm_array_task_id"
  exit 1
fi

# Select one .sync file based on the Slurm array task ID and remove the .sync name from the end so the new name is 
# only the scaffold name. 
file="${files[$slurm_array_task_id]}"
basename="$(basename "$file" .sync)"

# Print which file this task is processing. 
echo "Running on file: $file"

# Run the PoPoolation2 FST script on that .sync file and write the output to the FST directory. 
# I specify the input file which corresponds to the Slurm task array, the output location and file name, and some quality control.
# "Min-count 10" will only consider alleles with at least 10 supporting reads. "Min-coverage 50" requires that there are at least 50 
# reads across the locus. "Max-coverage 200" ignores positions that have coverage reads over 200, as these may be faulty. 
# "step-size 1" calculates FST SNP-by-SNP instead of using windows. "Pool-size 50:50" tells PoPoolation2 that the pool sizes 
# include 50 and 50 chromosomes, which translates to 25 diploid individuals per pool. This is the ratio used in patches 
# JR2, JR3, and JR4, whereas JR1 had a ratio of 50: 8 because only four white individuals were apart of the pool. 
perl "$script" \
  --input "$file" \
  --output "$outdir/${basename}.fst" \
  --min-count 10 \
  --min-coverage 50 \
  --max-coverage 200 \
  --window-size 1 \
  --step-size 1 \
  --pool-size 50:50
